### ISSUE TITLE
errors in logs

### ISSUE THREAD

**Issue by neoclust** [pulse-project/pulse-xmpp-agent#2]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sleekxmpp/xmlstream/xmlstream.py", line 1695, in _event_runner
    handler(*args[0], **args[1])
  File "/usr/lib/python2.7/dist-packages/pulse_xmpp_agent/agentxmpp.py", line 542, in update_plugin
    dataobj  = self.seachInfoMachine()
  File "/usr/lib/python2.7/dist-packages/pulse_xmpp_agent/agentxmpp.py", line 878, in seachInfoMachine
    'remoteservice' : protoandport(),
  File "/usr/lib/python2.7/dist-packages/pulse_xmpp_agent/lib/utils.py", line 1145, in protoandport
    if cux.status == psutil.CONN_LISTEN and ip == "0.0.0.0":
AttributeError: 'tuple' object has no attribute 'port'

**Comment by neoclust** [comment]
seems fixed
